sonar.organization = nick2bad4u
sonar.projectKey = Nick2bad4u_stylelint-plugin-file-progress
sonar.projectName = stylelint-plugin-file-progress
sonar.sources = src
sonar.tests = test
sonar.test.inclusions = test/**
sonar.javascript.lcov.reportPaths = coverage/lcov.info
sonar.typescript.tsconfigPaths = tsconfig.json,tsconfig.build.json
sonar.sourceEncoding = UTF-8
sonar.qualitygate.wait = true

sonar.host.url = https://sonarcloud.io
