import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
    documentation: [{ dirName: ".", type: "autogenerated" }],
} satisfies SidebarsConfig;
export default sidebars;
