import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import project from "./src/data/project.json" with { type: "json" };

const sidebars = {
    documentation: [
        {
            className: "sfp-sidebar-section sfp-tone-teal",
            collapsed: false,
            items: [
                { id: "index", label: "Overview", type: "doc" },
                {
                    id: "getting-started",
                    label: "Getting started",
                    type: "doc",
                },
                {
                    id: "compatibility",
                    label: "Compatibility & metrics",
                    type: "doc",
                },
                {
                    id: "troubleshooting",
                    label: "Troubleshooting",
                    type: "doc",
                },
            ],
            label: "Start here",
            type: "category",
        },
        {
            className: "sfp-sidebar-section sfp-tone-blue",
            collapsed: false,
            items: [
                {
                    id: "activate",
                    label: "file-progress/activate",
                    type: "doc",
                },
                { id: "demos", label: "Terminal demo gallery", type: "doc" },
            ],
            label: "Rule & display",
            type: "category",
        },
        {
            className: "sfp-sidebar-section sfp-tone-violet",
            collapsed: false,
            items: project.presets.map((preset) => ({
                className: `sfp-tone-${preset.tone}`,
                id: `presets/${preset.name}`,
                label: preset.label,
                type: "doc" as const,
            })),
            label: "Presets",
            link: { id: "presets", type: "doc" },
            type: "category",
        },
        {
            className: "sfp-sidebar-section sfp-tone-amber",
            collapsed: true,
            items: [
                {
                    id: "developer/contributing",
                    label: "Contributing",
                    type: "doc",
                },
                {
                    id: "developer/quality-review",
                    label: "Quality review",
                    type: "doc",
                },
                {
                    items: [
                        { dirName: "developer/api", type: "autogenerated" },
                    ],
                    label: "API reference",
                    link: { id: "developer/api/index", type: "doc" },
                    type: "category",
                },
            ],
            label: "Development",
            type: "category",
        },
        {
            className: "sfp-sidebar-section sfp-tone-pink",
            collapsed: true,
            items: [
                {
                    id: "resources",
                    label: "Inspectors & project links",
                    type: "doc",
                },
                {
                    href: "https://nick2bad4u.github.io/eslint-plugin-file-progress-2/",
                    label: "ESLint File Progress ↗",
                    type: "link",
                },
                {
                    href: "https://nick2bad4u.github.io/eslint-plugin-typefest/",
                    label: "ESLint Typefest ↗",
                    type: "link",
                },
                {
                    href: "https://github.com/Nick2bad4u/stylelint-plugin-file-progress/issues",
                    label: "Issues & feedback ↗",
                    type: "link",
                },
            ],
            label: "Ecosystem & support",
            type: "category",
        },
    ],
} satisfies SidebarsConfig;
export default sidebars;
